// Post-quantum hybrid envelopes (FIPS 203 ML-KEM-768 + X25519).
//
// The audit (POST_QUANTUM_AUDIT.md) found the key-envelope layer to be the
// biggest harvest-now-decrypt-later exposure: everything wrapped with static
// X25519 stays readable to a future quantum computer. This spec proves the
// replacement actually works in the browser the app ships:
//   * the vendored @noble library reproduces the cross-language KAT fixture
//     (generated by tools/gen-pq-kat.mjs and re-checked against RustCrypto by
//     server unit tests),
//   * envelope v2 round-trips, fails closed on wrong keys / tampering, and the
//     v1 path still works for peers without a published PQ key,
//   * registration publishes the derived ML-KEM identity key, /api/identity
//     returns it, and the publish endpoint validates and authenticates,
//   * two real accounts exchange a hybrid envelope through their published keys.
import { test, expect, Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import * as path from 'node:path';
import { apiLogin } from './_auth-helpers';

const BASE = 'https://localhost:3443';
const KAT = JSON.parse(
    readFileSync(path.join(__dirname, '..', 'server', 'tests', 'fixtures', 'pq-kat.json'), 'utf8'),
);

async function registerUser(page: Page, uname: string) {
    await page.goto(BASE + '/login.html');
    await page.waitForTimeout(400);
    await page.click('#show-register');
    await page.fill('#register-username', uname);
    await page.fill('#register-password', 'password123');
    await page.fill('#register-confirm-password', 'password123');
    await page.click('#register-form button[type="submit"]');
    await page.waitForURL('**/index.html', { timeout: 30000 });
    const token = await page.evaluate(() => localStorage.getItem('token'));
    expect(token).toBeTruthy();
    return token as string;
}

test.describe('post-quantum hybrid envelopes', () => {
    test('the vendored library matches the cross-language KAT fixture', async ({ page }) => {
        await page.goto(BASE + '/login.html');
        const result = await page.evaluate(async (kat) => {
            const hex = (u8: Uint8Array) =>
                Array.from(u8).map((b) => b.toString(16).padStart(2, '0')).join('');
            const fromHex = (s: string) =>
                new Uint8Array((s.match(/../g) || []).map((h) => parseInt(h, 16)));
            const E = (window as any).E2ECrypto;
            await E.pqReady();
            const PQ = (window as any).NoblePQ;

            const kp = PQ.ml_kem768.keygen(fromHex(kat.ml_kem_768.seed_hex));
            const dec = PQ.ml_kem768.decapsulate(
                fromHex(kat.ml_kem_768.ciphertext_hex),
                kp.secretKey,
            );

            const dsaKp = PQ.ml_dsa65.keygen(fromHex(kat.ml_dsa_65.seed_hex));
            const sig = fromHex(kat.ml_dsa_65.signature_hex);
            const msg = new TextEncoder().encode(kat.ml_dsa_65.message_utf8);
            const tampered = new TextEncoder().encode(kat.ml_dsa_65.tampered_message_utf8);
            const sigOk =
                PQ.ml_dsa65.verify(sig, msg, dsaKp.publicKey) ||
                PQ.ml_dsa65.verify(msg, sig, dsaKp.publicKey);
            const sigBad =
                PQ.ml_dsa65.verify(sig, tampered, dsaKp.publicKey) ||
                PQ.ml_dsa65.verify(tampered, sig, dsaKp.publicKey);

            // Escrow v2 KDF expression: SHA-256(label || dh || ss || kem_ct ||
            // epk || recipient_pub) — the same bytes Rust hashes.
            const cat = (...arrs: Uint8Array[]) => {
                const out = new Uint8Array(arrs.reduce((a, b) => a + b.length, 0));
                let off = 0;
                for (const a of arrs) {
                    out.set(a, off);
                    off += a.length;
                }
                return out;
            };
            const ikm = cat(
                new TextEncoder().encode('e2e-escrow-v2|'),
                fromHex(kat.escrow_v2.dh_hex),
                fromHex(kat.escrow_v2.shared_secret_hex),
                fromHex(kat.escrow_v2.kem_ciphertext_hex),
                fromHex(kat.escrow_v2.epk_hex),
                fromHex(kat.escrow_v2.recipient_public_hex),
            );
            const keyHex = await E.sha256Hex(ikm);

            return {
                kemPub: hex(kp.publicKey),
                kemSecretDecap: hex(dec),
                dsaPub: hex(dsaKp.publicKey),
                sigOk,
                sigBad,
                keyHex,
            };
        }, KAT);

        expect(result.kemPub).toBe(KAT.ml_kem_768.public_key_hex);
        expect(result.kemSecretDecap).toBe(KAT.ml_kem_768.shared_secret_hex);
        expect(result.dsaPub).toBe(KAT.ml_dsa_65.public_key_hex);
        expect(result.sigOk).toBe(true);
        expect(result.sigBad).toBe(false);
        expect(result.keyHex).toBe(KAT.escrow_v2.key_sha256_hex);
    });

    test('v2 round-trips, fails closed on the wrong key, and keeps v1 readable', async ({ page }) => {
        await page.goto(BASE + '/login.html');
        const r = await page.evaluate(async () => {
            const E = (window as any).E2ECrypto;
            await E.pqReady();
            const alice = E.x25519GenerateKeyPair();
            const bob = E.x25519GenerateKeyPair();
            const carol = E.x25519GenerateKeyPair();
            const bobPqPub = E.getIdentityPqKeyPair(bob.privateKey).publicKey;

            // Cross-user hybrid envelope (the server-key distribution shape).
            const enc = E.envelopeEncrypt('hello bob', bob.publicKey, alice.privateKey, bobPqPub);
            const dec = E.envelopeDecrypt(enc.ciphertext, bob.privateKey, alice.publicKey, enc.nonce);

            // A different ML-KEM secret must not open it (fails closed)…
            let wrongKeyRejected = false;
            try {
                E.envelopeDecrypt(
                    enc.ciphertext, bob.privateKey, alice.publicKey, enc.nonce,
                    E.getIdentityPqSecretKey(carol.privateKey),
                );
            } catch (_) { wrongKeyRejected = true; }

            // …and neither must a flipped ciphertext bit.
            const tampered = new Uint8Array(E.base64ToArrayBuffer(enc.ciphertext));
            tampered[tampered.length - 5] ^= 0x01;
            let tamperRejected = false;
            try {
                E.envelopeDecrypt(E.arrayBufferToBase64(tampered), bob.privateKey, alice.publicKey, enc.nonce);
            } catch (_) { tamperRejected = true; }

            // v1 fallback: no published PQ key → byte-identical legacy envelope.
            const v1 = E.envelopeEncrypt('legacy', bob.publicKey, alice.privateKey);
            const v1dec = E.envelopeDecrypt(v1.ciphertext, bob.privateKey, alice.publicKey, v1.nonce);

            // Self-encryption upgrades automatically (recipient == sender).
            const self = E.envelopeEncrypt('to myself', alice.publicKey, alice.privateKey);
            const selfDec = E.envelopeDecrypt(self.ciphertext, alice.privateKey, alice.publicKey, self.nonce);

            const magic = (b64: string) =>
                Array.from(new Uint8Array(E.base64ToArrayBuffer(b64)).slice(0, 6))
                    .map((c: number) => String.fromCharCode(c)).join('');

            return {
                dec: new TextDecoder().decode(dec),
                crossUserIsV2: !!enc.pq && magic(enc.ciphertext) === 'E2EPQv',
                wrongKeyRejected,
                tamperRejected,
                v1IsNotV2: !v1.pq && magic(v1.ciphertext) !== 'E2EPQv',
                v1dec: new TextDecoder().decode(v1dec),
                selfIsV2: !!self.pq,
                selfDec: new TextDecoder().decode(selfDec),
            };
        });

        expect(r.dec).toBe('hello bob');
        expect(r.crossUserIsV2).toBe(true);
        expect(r.wrongKeyRejected).toBe(true);
        expect(r.tamperRejected).toBe(true);
        expect(r.v1IsNotV2).toBe(true);
        expect(r.v1dec).toBe('legacy');
        expect(r.selfIsV2).toBe(true);
        expect(r.selfDec).toBe('to myself');
    });

    test('registration publishes the derived ML-KEM identity key', async ({ page }) => {
        const uname = 'pqreg_' + Date.now();
        const token = await registerUser(page, uname);

        const info = await page.evaluate(async () => {
            const E = (window as any).E2ECrypto;
            await E.pqReady();
            const identity = E.getIdentityKeyPair();
            const myPq = E.getIdentityPqPublicKeyB64(identity.privateKey);
            const me = JSON.parse(localStorage.getItem('user') || '{}');
            const res = await fetch('/api/identity/' + me.id);
            const data = await res.json();
            return { id: me.id, myPq, serverPq: data.identity_pq_public_key };
        });

        // The server stored exactly the key the client derives, and the identity
        // endpoint serves it to peers.
        expect(info.serverPq).toBe(info.myPq);
        expect(info.myPq.length).toBe(Math.ceil(1184 / 3) * 4);

        // The capability flag tells peers v2 is available.
        const cfg = await page.request.get(BASE + '/api/client-config');
        const cfgJson = await cfg.json();
        expect(cfgJson.pq_envelope).toBe(true);
        expect(cfgJson.pq_kem).toBe('ML-KEM-768');

        // Idempotent republish works; a wrong-size key is rejected; the endpoint
        // requires authentication.
        const ok = await page.request.post(BASE + '/api/identity/pq-key', {
            headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
            data: { identity_pq_public_key: info.myPq },
        });
        expect(ok.status()).toBe(200);
        const bad = await page.request.post(BASE + '/api/identity/pq-key', {
            headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
            data: { identity_pq_public_key: 'AAAA' },
        });
        expect(bad.status()).toBe(400);
        const anon = await page.request.post(BASE + '/api/identity/pq-key', {
            headers: { 'Content-Type': 'application/json' },
            data: { identity_pq_public_key: info.myPq },
        });
        expect(anon.status()).toBe(401);
    });

    // Server-side companion to the client's always-hybrid registration: a
    // classical-only identity key must be refused. Otherwise an API client
    // could create an account that every sender addresses with the v1
    // X25519-only envelope — the exact harvest-now-decrypt-later hole the
    // hybrid layer closes — and nothing would ever upgrade it.
    test('a classical-only identity key is refused at registration', async ({ request }) => {
        const hybridLoginKey = () =>
            JSON.stringify({
                v: 2,
                ed25519: Buffer.alloc(32, 7).toString('base64'),
                ml_dsa_65: Buffer.alloc(1952, 11).toString('base64'),
            });
        const base = () => ({
            password: 'x'.repeat(64),
            login_public_key: hybridLoginKey(),
        });

        const classicalOnly = await request.post(BASE + '/api/register', {
            data: {
                ...base(),
                username: 'pqclassical_' + Date.now(),
                identity_public_key: Buffer.alloc(32, 3).toString('base64'),
            },
        });
        expect(classicalOnly.status(), 'X25519 alone must not be accepted').toBe(400);
        expect((await classicalOnly.json()).error).toContain('identity_pq_public_key');

        // A malformed X25519 half is rejected too…
        const shortKey = await request.post(BASE + '/api/register', {
            data: {
                ...base(),
                username: 'pqshort_' + Date.now(),
                identity_public_key: Buffer.alloc(16, 3).toString('base64'),
                identity_pq_public_key: Buffer.alloc(1184, 5).toString('base64'),
            },
        });
        expect(shortKey.status()).toBe(400);
        expect((await shortKey.json()).error).toContain('32-byte');

        // …while the hybrid pair the shipped client sends is accepted.
        const hybrid = await request.post(BASE + '/api/register', {
            data: {
                ...base(),
                username: 'pqhybrid_' + Date.now(),
                identity_public_key: Buffer.alloc(32, 3).toString('base64'),
                identity_pq_public_key: Buffer.alloc(1184, 5).toString('base64'),
            },
        });
        expect(hybrid.status(), 'hybrid X25519 + ML-KEM-768 registers').toBe(201);
    });

    test('two accounts exchange a hybrid envelope through their published keys', async ({ browser }) => {
        const ctxA = await browser.newContext({ ignoreHTTPSErrors: true });
        const ctxB = await browser.newContext({ ignoreHTTPSErrors: true });
        try {
            const pageA = await ctxA.newPage();
            const pageB = await ctxB.newPage();
            await registerUser(pageA, 'pqalice_' + Date.now());
            await registerUser(pageB, 'pqbob_' + Date.now());

            const alice = await pageA.evaluate(async () => {
                const E = (window as any).E2ECrypto;
                await E.pqReady();
                const identity = E.getIdentityKeyPair();
                const me = JSON.parse(localStorage.getItem('user') || '{}');
                return {
                    id: me.id,
                    priv: E.arrayBufferToBase64(identity.privateKey),
                    pub: E.arrayBufferToBase64(identity.publicKey),
                };
            });
            const bob = await pageB.evaluate(async () => {
                const E = (window as any).E2ECrypto;
                await E.pqReady();
                const identity = E.getIdentityKeyPair();
                const me = JSON.parse(localStorage.getItem('user') || '{}');
                return {
                    id: me.id,
                    priv: E.arrayBufferToBase64(identity.privateKey),
                    pub: E.arrayBufferToBase64(identity.publicKey),
                    pqPub: E.getIdentityPqPublicKeyB64(identity.privateKey),
                };
            });
            expect(bob.pqPub.length).toBe(Math.ceil(1184 / 3) * 4);

            // Alice fetches Bob's published keys and wraps a key for him — the
            // exact flow used for server keys, channel keys and soundboard clips.
            const enc = await pageA.evaluate(async ({ bobId }) => {
                const E = (window as any).E2ECrypto;
                await E.pqReady();
                const identity = E.getIdentityKeyPair();
                const res = await fetch('/api/identity/' + bobId);
                const data = await res.json();
                const recipientPub = new Uint8Array(E.base64ToArrayBuffer(data.identity_public_key));
                const recipientPq = E.pqPublicKeyFromB64(data.identity_pq_public_key);
                const sealed = E.envelopeEncrypt('hybrid channel key', recipientPub, identity.privateKey, recipientPq);
                return { ciphertext: sealed.ciphertext, nonce: sealed.nonce, isV2: !!sealed.pq, senderPub: E.arrayBufferToBase64(identity.publicKey) };
            }, { bobId: bob.id });

            expect(enc.isV2).toBe(true);

            // Bob decrypts with his own identity key — no extra arguments, the
            // PQ secret is derived inside envelopeDecrypt.
            const bobPriv = await pageB.evaluate(() => {
                const E = (window as any).E2ECrypto;
                const identity = E.getIdentityKeyPair();
                return E.arrayBufferToBase64(identity.privateKey);
            });
            const plain = await pageB.evaluate(({ ciphertext, nonce, senderPub, privB64 }) => {
                const E = (window as any).E2ECrypto;
                const pt = E.envelopeDecrypt(
                    ciphertext,
                    new Uint8Array(E.base64ToArrayBuffer(privB64)),
                    new Uint8Array(E.base64ToArrayBuffer(senderPub)),
                    nonce,
                );
                return new TextDecoder().decode(pt);
            }, { ...enc, privB64: bobPriv });
            expect(plain).toBe('hybrid channel key');
            void alice;
        } finally {
            await ctxA.close();
            await ctxB.close();
        }
    });
});

test.describe('post-quantum transport (TLS)', () => {
    // Phase 0.1 of the audit: the app's whole PQ story starts from a transport
    // leg that is actually hybrid. Offer ONLY X25519MLKEM768 and require the
    // server to negotiate it — if the rustls provider ever stops including the
    // group, the handshake fails and this test fails with it. `openssl` is
    // assumed on PATH, the same way this suite already assumes python3.
    test('the server negotiates the X25519MLKEM768 hybrid group', async () => {
        // openssl prints the connection report to stderr, so both streams are
        // concatenated (a failed handshake also lands there).
        const r = spawnSync(
            'openssl',
            ['s_client', '-connect', '127.0.0.1:3443', '-groups', 'X25519MLKEM768', '-brief'],
            { input: '', encoding: 'utf8' },
        );
        const out = String(r.stdout || '') + String(r.stderr || '');
        expect(out, 'the TLS handshake must complete with the hybrid group offered').toContain(
            'Protocol version: TLSv1.3',
        );
        expect(out, 'the negotiated group must be the hybrid one').toContain(
            'Negotiated TLS1.3 group: X25519MLKEM768',
        );
    });
});

test.describe('hybrid login signatures (PQ Phase 2)', () => {
    test('registration stores a v2 login key, and a v2 account refuses an Ed25519-only login', async ({ page }) => {
        const uname = 'pqlogin_' + Date.now();
        await registerUser(page, uname);

        // The stored login key is the hybrid blob (v2), not the legacy bare key.
        const params = await page.evaluate(async (u) => {
            return await (await fetch('/api/auth-params/' + encodeURIComponent(u))).json();
        }, uname);
        const blob = JSON.parse(params.login_public_key);
        expect(blob.v).toBe(2);
        expect(blob.ed25519, 'Ed25519 half present').toBeTruthy();
        expect(blob.ml_dsa_65, 'ML-DSA-65 half present').toBeTruthy();

        // Craft a fresh body with ONLY the Ed25519 signature — the pre-hybrid
        // client shape. The server must refuse it: a recorded login must stay
        // unreplayable even after Ed25519 falls to a quantum computer.
        const edOnly = await page.evaluate(async (u) => {
            const E = (window as any).E2ECrypto;
            const p = await (await fetch('/api/auth-params/' + encodeURIComponent(u))).json();
            const hk = E.decryptWithPassword(p.encrypted_hash_key, 'password123', p.hash_key_salt, p.hash_key_nonce);
            const bytes = new Uint8Array(E.base64ToArrayBuffer(hk));
            return {
                username: u,
                login_nonce: p.login_nonce,
                login_signature: E.signLoginChallenge(bytes, 'password123', u, p.login_nonce),
            };
        }, uname);
        const refused = await page.request.post(BASE + '/api/login', {
            headers: { 'Content-Type': 'application/json' },
            data: edOnly,
        });
        expect(refused.status(), 'a v2 account cannot log in without the ML-DSA signature').toBe(401);

        // The real client builds both signatures over the same nonce; that
        // login succeeds end-to-end.
        const ok = await apiLogin(page, uname, 'password123');
        expect(ok.status(), 'the hybrid login body succeeds').toBe(200);
    });
});
