// Generate the cross-language post-quantum KAT fixture used by both sides:
//
//     node tools/gen-pq-kat.mjs
//
// Output: server/tests/fixtures/pq-kat.json
//
// The client runs the vendored @noble/post-quantum (static/libs/*) and the
// server runs RustCrypto ml-kem/ml-dsa. They are independent implementations of
// FIPS 203/204, so the only way to know they will interoperate is to have one
// pin values the other recomputes. This script generates those values with the
// JS side; the Rust unit tests assert the Rust side produces/accepts them, and
// tests/pq-envelopes.spec.ts asserts the JS side still does too. A
// spec-visible drift in either implementation fails CI instead of breaking live
// traffic.
//
// The escrow KDF vector pins the exact byte layout shared by
// db.rs::encrypt_notification_payload and E2ECrypto.decryptEscrowPayload:
//     SHA-256("e2e-escrow-v2|" || dh || ss || kem_ct || epk || recipient_pub)
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const hex = (u8) => Buffer.from(u8).toString('hex');
const seq = (start, len) => Uint8Array.from({ length: len }, (_, i) => (start + i) & 0xff);

// Node only treats a file as ESM when it ends in .mjs (or a package.json says
// so), and the vendored closure uses relative imports between a main file and
// its ./noble/ dependencies. Copy the closure into a temp tree as .mjs with the
// specifiers rewritten to match, then import from there.
const tmp = join(tmpdir(), 'pq-kat-' + Date.now());
mkdirSync(join(tmp, 'noble'), { recursive: true });
// Rewrites both `from "./x.js"` and side-effect `import "./x.js"` specifiers.
const toMjs = (text) => text.replace(/"(\.\/[^"]+)\.js"/g, '"$1.mjs"');
for (const f of readdirSync(join(ROOT, 'static/libs/noble'))) {
    if (!f.endsWith('.js')) continue;
    writeFileSync(join(tmp, 'noble', f.replace(/\.js$/, '.mjs')),
        toMjs(readFileSync(join(ROOT, 'static/libs/noble', f), 'utf8')));
}
writeFileSync(join(tmp, 'mlkem.mjs'),
    toMjs(readFileSync(join(ROOT, 'static/libs/noble-post-quantum-0.7.1-ml-kem.js'), 'utf8')));
writeFileSync(join(tmp, 'mldsa.mjs'),
    toMjs(readFileSync(join(ROOT, 'static/libs/noble-post-quantum-0.7.1-ml-dsa.js'), 'utf8')));
const { ml_kem768 } = await import(pathToFileURL(join(tmp, 'mlkem.mjs')).href);
const { ml_dsa65 } = await import(pathToFileURL(join(tmp, 'mldsa.mjs')).href);

// ---- ML-KEM-768: deterministic keygen from a 64-byte seed + one encapsulation.
const kemSeed = seq(0x00, 64);
const kemKp = ml_kem768.keygen(kemSeed);
const kemEnc = ml_kem768.encapsulate(kemKp.publicKey);
const kemDec = ml_kem768.decapsulate(kemEnc.cipherText, kemKp.secretKey);
if (hex(kemDec) !== hex(kemEnc.sharedSecret)) throw new Error('ML-KEM roundtrip failed');
if (kemEnc.cipherText.length !== 1088) throw new Error('unexpected ML-KEM-768 ciphertext size');

// ---- ML-DSA-65: deterministic keygen from a 32-byte seed + one signature.
const dsaSeed = seq(0xa0, 32);
const dsaKp = ml_dsa65.keygen(dsaSeed);
const dsaMsg = new TextEncoder().encode('e2e-login-v1|alice|fixture-nonce');
const dsaSig = ml_dsa65.sign(dsaMsg, dsaKp.secretKey);
// Noble's verify() argument order is (signature, message, publicKey). Try the
// alternate order too so this generator survives an upstream reordering; the
// pinned signature is only written once one of them verifies.
const dsaOk = ml_dsa65.verify(dsaSig, dsaMsg, dsaKp.publicKey)
    || ml_dsa65.verify(dsaMsg, dsaSig, dsaKp.publicKey);
if (!dsaOk) throw new Error('ML-DSA verify failed with both argument orders');
const dsaTampered = new TextEncoder().encode('e2e-login-v1|alice|other-nonce');
const dsaBad = ml_dsa65.verify(dsaSig, dsaTampered, dsaKp.publicKey)
    || ml_dsa65.verify(dsaTampered, dsaSig, dsaKp.publicKey);
if (dsaBad) throw new Error('ML-DSA accepted a tampered message');
if (dsaSig.length !== 3309) throw new Error('unexpected ML-DSA-65 signature size');

// ---- Escrow v2 KDF vector.
const dh = seq(0x11, 32);
const epk = seq(0x22, 32);
const recipientPub = seq(0x33, 32);
const label = new TextEncoder().encode('e2e-escrow-v2|');
const ikm = Buffer.concat([
    Buffer.from(label),
    Buffer.from(dh),
    Buffer.from(kemEnc.sharedSecret),
    Buffer.from(kemEnc.cipherText),
    Buffer.from(epk),
    Buffer.from(recipientPub),
]);
const escrowKey = createHash('sha256').update(ikm).digest('hex');

const out = {
    _note: 'Generated by tools/gen-pq-kat.mjs — do not edit by hand.',
    source: '@noble/post-quantum 0.7.1 (vendored in static/libs)',
    ml_kem_768: {
        seed_hex: hex(kemSeed),
        public_key_hex: hex(kemKp.publicKey),
        ciphertext_hex: hex(kemEnc.cipherText),
        shared_secret_hex: hex(kemEnc.sharedSecret),
    },
    ml_dsa_65: {
        seed_hex: hex(dsaSeed),
        public_key_hex: hex(dsaKp.publicKey),
        message_utf8: 'e2e-login-v1|alice|fixture-nonce',
        signature_hex: hex(dsaSig),
        tampered_message_utf8: 'e2e-login-v1|alice|other-nonce',
    },
    escrow_v2: {
        dh_hex: hex(dh),
        shared_secret_hex: hex(kemEnc.sharedSecret),
        kem_ciphertext_hex: hex(kemEnc.cipherText),
        epk_hex: hex(epk),
        recipient_public_hex: hex(recipientPub),
        key_sha256_hex: escrowKey,
    },
};

const dest = join(ROOT, 'server', 'tests', 'fixtures', 'pq-kat.json');
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n');
console.log('wrote ' + dest);
